cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --time={resources.time}
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}
    --output=logs/{rule}/{rule}-%j.out
    --parsable
    # can't use wildcards in group jobs
    # see https://github.com/snakemake/snakemake/issues/1406
    # --job-name=smk-{rule}-{wildcards}
    # --output=logs/{rule}/{rule}-{wildcards}-%j.out
cluster-status:
  status-sacct-robust.sh
default-resources:
  - partition=physical
  - mem_mb=8000
  - time=10
restart-times: 0
max-jobs-per-second: 100
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-singularity: True
singularity-args: "-B $PWD,$TMPDIR,/data --nv -H $(mktemp -d) --pwd $PWD --containall --cleanenv --writable-tmpfs"
